import './App.css'
import { Composer } from './features/chat/components/Composer'
import { ConversationView } from './features/chat/components/ConversationView'
import { ModeSwitch } from './features/chat/components/ModeSwitch'
import { PersonaPanel } from './features/chat/components/PersonaPanel'
import { useLocalChat } from './features/chat/hooks/useLocalChat'
import type { RuntimeTask, TaskStage } from './features/chat/model/types'

function formatLastEventLabel(timestamp: string | undefined) {
  if (!timestamp) return 'Awaiting first packet'
  const parsed = Date.parse(timestamp)
  if (Number.isNaN(parsed)) return timestamp

  return new Intl.DateTimeFormat(undefined, {
    hour: '2-digit',
    minute: '2-digit',
    month: 'short',
    day: 'numeric',
  }).format(parsed)
}

function formatRelativeLabel(timestamp: string | undefined) {
  if (!timestamp) return 'No recent signal'
  const parsed = Date.parse(timestamp)
  if (Number.isNaN(parsed)) return timestamp

  const diffMs = Date.now() - parsed
  const diffMinutes = Math.round(diffMs / 60000)

  if (diffMinutes <= 1) return 'just now'
  if (diffMinutes < 60) return `${diffMinutes} min ago`

  const diffHours = Math.round(diffMinutes / 60)
  if (diffHours < 24) return `${diffHours} hr ago`

  const diffDays = Math.round(diffHours / 24)
  return `${diffDays} day${diffDays === 1 ? '' : 's'} ago`
}

function formatStageLabel(stage: TaskStage) {
  return stage.charAt(0).toUpperCase() + stage.slice(1)
}

function describeTask(task: RuntimeTask) {
  const parts = [
    `${formatStageLabel(task.stage)} stage`,
    task.lane,
    task.owner,
    `due ${task.due}`,
  ]

  if (task.needsUserInput) parts.push('waiting on user')
  if (task.readyToReport) parts.push('ready to report')

  return parts.join(' · ')
}

function App() {
  const {
    activeMode,
    activeModeId,
    apiState,
    draft,
    historyCursorLabel,
    inputHistory,
    isResponding,
    messages,
    modes,
    rawMessages,
    recentActivity,
    runtimeContext,
    runtimeNotes,
    runtimeStatus,
    runtimeTasks,
    suggestedPrompts,
    transportPreview,
    setActiveModeId,
    setDraft,
    submitMessage,
    cycleHistory,
  } = useLocalChat()

  const latestMessage = rawMessages[rawMessages.length - 1]
  const systemMessages = rawMessages.filter((message) => message.role === 'system').length
  const taskBreakdown = runtimeContext?.surfaces.taskBreakdown
  const taskStageBreakdown = runtimeContext?.surfaces.taskStageBreakdown
  const attentionCounts = runtimeContext?.surfaces.attentionCounts
  const runtimeCards = runtimeStatus?.cards ?? []
  const environmentLabel = runtimeStatus?.environment ?? 'offline'
  const lastEventLabel = formatLastEventLabel(latestMessage?.timestamp)
  const runtimeRecentActivity = recentActivity.filter((item) => item.source === 'runtime')
  const seededRecentActivity = recentActivity.filter((item) => item.source === 'seeded-demo')
  const runtimeNotesLive = runtimeNotes.filter((note) => note.source === 'runtime')
  const seededNotes = runtimeNotes.filter((note) => note.source === 'seeded-demo')
  const runtimeTasksLive = runtimeTasks.filter((task) => task.source === 'runtime')
  const seededTasks = runtimeTasks.filter((task) => task.source === 'seeded-demo')
  const activeExecutionTasks = runtimeTasks.filter((task) => task.status !== 'Blocked' && task.status !== 'Done' && !task.needsUserInput)
  const waitingOnUserTasks = runtimeTasks.filter((task) => task.needsUserInput && task.status !== 'Done')
  const blockedTasks = runtimeTasks.filter((task) => task.status === 'Blocked')
  const readyToReportTasks = runtimeTasks.filter((task) => task.readyToReport)
  const modeCoverage = runtimeContext?.chat.modes.length ?? modes.length
  const activeModeSurface = activeMode.label
  const activeModeAccent = activeMode.accent
  const modelLaneLabel =
    apiState === 'connected'
      ? 'Server stub response'
      : transportPreview.provider === 'Local simulator'
        ? 'Local simulator'
        : transportPreview.provider
  const modelTruthLabel =
    apiState === 'connected'
      ? 'Model identity not yet exposed by backend. Current replies are honest server-side placeholder responses.'
      : 'No backend model truth available. Responses are generated by the local simulator seam.'

  const projectAreas = [
    {
      id: 'delivery',
      title: 'Active execution',
      value: `${activeExecutionTasks.length} tasks`,
      detail:
        activeExecutionTasks[0]?.title ?? 'No active runtime tasks yet. The board is ready when real task state appears.',
    },
    {
      id: 'waiting',
      title: 'Waiting on user',
      value: `${waitingOnUserTasks.length} items`,
      detail:
        waitingOnUserTasks[0]?.title ?? 'Nothing is currently marked as needing operator input.',
    },
    {
      id: 'blocked',
      title: 'Blocked work',
      value: `${blockedTasks.length} items`,
      detail:
        blockedTasks[0]?.title ?? 'No blocked tasks are exposed right now.',
    },
    {
      id: 'reporting',
      title: 'Ready to report',
      value: `${readyToReportTasks.length} items`,
      detail:
        readyToReportTasks[0]?.title ?? 'Nothing completed is waiting for operator reporting.',
    },
  ]

  const liveNowFeed = [
    ...runtimeRecentActivity.map((item) => ({
      id: item.id,
      title: item.title,
      detail: item.detail,
      status: item.status,
      meta: `${item.type} · ${formatRelativeLabel(item.timestamp)}`,
      source: item.source,
    })),
    ...runtimeNotesLive.map((note) => ({
      id: note.id,
      title: note.title,
      detail: note.body,
      status: 'logged' as const,
      meta: `[${note.tag}] ${formatRelativeLabel(note.updatedAt)}`,
      source: note.source,
    })),
  ].slice(0, 6)
  const baselineFeed = [
    ...seededRecentActivity.map((item) => ({
      id: item.id,
      title: item.title,
      detail: item.detail,
      status: item.status,
      meta: `seeded baseline · ${formatLastEventLabel(item.timestamp)}`,
      source: item.source,
    })),
    ...seededNotes.map((note) => ({
      id: note.id,
      title: note.title,
      detail: note.body,
      status: 'logged' as const,
      meta: `[${note.tag}] seeded baseline`,
      source: note.source,
    })),
  ].slice(0, 4)
  const agentRoster = [
    {
      id: 'sentinel',
      label: 'Sentinel core',
      state: isResponding ? 'engaged' : apiState === 'connected' ? 'synced' : 'local-only',
      detail: `${activeMode.label} · ${modelLaneLabel}`,
    },
    {
      id: 'runtime',
      label: 'Runtime spine',
      state: apiState === 'connected' ? 'live' : 'standby',
      detail: runtimeContext
        ? `${runtimeContext.session.hostLabel} · ${runtimeContext.session.persistenceDriver}`
        : 'Awaiting bootstrap context',
    },
    {
      id: 'task-grid',
      label: 'Task grid',
      state: blockedTasks.length > 0 ? 'watch' : 'steady',
      detail: `${runtimeTasks.length} tracked tasks · ${waitingOnUserTasks.length} waiting on user`,
    },
    {
      id: 'model-monitor',
      label: 'System/model monitor',
      state: apiState === 'connected' ? 'truthful' : 'fallback',
      detail: modelTruthLabel,
    },
  ]

  const runtimeSummary = runtimeContext
    ? `${runtimeContext.session.hostLabel} · ${runtimeContext.chat.messageCount} persisted messages · ${runtimeTasksLive.length} live tasks / ${seededTasks.length} seeded baseline · ${runtimeRecentActivity.length} live updates`
    : 'Server-derived session context not available yet. Local shell remains armed.'

  const boardGroups = [
    {
      id: 'active',
      title: 'Active now',
      tone: 'live',
      description: 'Work currently in motion without a user dependency or hard block.',
      tasks: activeExecutionTasks,
    },
    {
      id: 'waiting',
      title: 'Waiting on user',
      tone: 'subtle',
      description: 'Items explicitly marked as needing Marco before they can move.',
      tasks: waitingOnUserTasks,
    },
    {
      id: 'blocked',
      title: 'Blocked',
      tone: 'warn',
      description: 'Work the runtime knows is blocked. No fake ETA, just visible friction.',
      tasks: blockedTasks,
    },
    {
      id: 'report',
      title: 'Completed, not yet reported',
      tone: 'subtle',
      description: 'Done work flagged as ready to report back through the operator loop.',
      tasks: readyToReportTasks,
    },
  ] as const

  const stageCards: Array<{ id: TaskStage; value: number; detail: string }> = [
    { id: 'queued', value: taskStageBreakdown?.queued ?? 0, detail: 'Captured, not started' },
    { id: 'inspecting', value: taskStageBreakdown?.inspecting ?? 0, detail: 'Reading or diagnosing' },
    { id: 'editing', value: taskStageBreakdown?.editing ?? 0, detail: 'Making changes' },
    { id: 'validating', value: taskStageBreakdown?.validating ?? 0, detail: 'Checking correctness' },
    { id: 'committing', value: taskStageBreakdown?.committing ?? 0, detail: 'Preparing local commit' },
    { id: 'pushing', value: taskStageBreakdown?.pushing ?? 0, detail: 'Ready for remote push' },
    { id: 'done', value: taskStageBreakdown?.done ?? 0, detail: 'Execution finished' },
  ]

  return (
    <div className="app-shell">
      <div className="shell-backdrop" aria-hidden="true">
        <div className="shell-backdrop__grid" />
        <div className="shell-backdrop__glow shell-backdrop__glow--one" />
        <div className="shell-backdrop__glow shell-backdrop__glow--two" />
      </div>

      <aside className="left-rail">
        <div className="brand-block">
          <p className="eyebrow">Sentinel Nexus // Command Center</p>
          <h1>Operator shell for decisive work, runtime visibility, and controlled execution.</h1>
          <p className="muted-copy">
            A cinematic local-first command surface with live backend truth when available and explicit seams where it is not.
          </p>
        </div>

        <div className="rail-card rail-card--accent">
          <div className="rail-card__header">
            <p className="eyebrow">System posture</p>
            <span className={`status-pill ${isResponding ? 'status-pill--live' : ''}`}>
              {isResponding ? 'LIVE TRAFFIC' : apiState === 'connected' ? 'SYNCED' : 'LOCAL FALLBACK'}
            </span>
          </div>
          <strong>{activeMode.label}</strong>
          <p className="muted-copy">{activeMode.intent}</p>
          <div className="rail-signal">
            <span className="rail-signal__label">Model lane</span>
            <span>{modelLaneLabel}</span>
          </div>
          <div className="rail-signal">
            <span className="rail-signal__label">Transport</span>
            <span>{transportPreview.provider}</span>
          </div>
        </div>

        <div className="rail-grid">
          <div className="rail-metric rail-metric--emphasis">
            <span>Active mode</span>
            <strong>{activeModeId.toUpperCase()}</strong>
            <small>{activeModeAccent}</small>
          </div>
          <div className="rail-metric rail-metric--emphasis">
            <span>Active model</span>
            <strong>{apiState === 'connected' ? 'SERVER STUB' : 'LOCAL SIM'}</strong>
            <small>{apiState === 'connected' ? 'backend truth boundary' : 'offline/local seam'}</small>
          </div>
          <div className="rail-metric">
            <span>History</span>
            <strong>{inputHistory.length.toString().padStart(2, '0')}</strong>
            <small>prompt recalls</small>
          </div>
          <div className="rail-metric">
            <span>Runtime</span>
            <strong>{environmentLabel}</strong>
            <small>{apiState === 'connected' ? 'API present' : 'simulated adapter'}</small>
          </div>
        </div>

        <div className="rail-card">
          <p className="eyebrow">Runtime sync</p>
          <strong>{apiState === 'connected' ? 'Backend connected' : 'Local continuity mode'}</strong>
          <p className="muted-copy">{runtimeSummary}</p>
        </div>

        <div className="rail-card">
          <p className="eyebrow">Operator board</p>
          <div className="stack-list">
            {projectAreas.map((area) => (
              <div key={area.id} className="stack-list__item">
                <span>{area.title}</span>
                <strong>{area.value}</strong>
                <small>{area.detail}</small>
              </div>
            ))}
          </div>
        </div>
      </aside>

      <main className="workspace">
        <section className="command-deck panel">
          <div>
            <p className="eyebrow">Command deck</p>
            <h2>Sentinel runtime monitor</h2>
            <p className="muted-copy">
              Real storage, message, task, and activity surfaces route in from the Nexus API when online. Offline, the shell keeps local composure and advertises the seam.
            </p>
          </div>

          <div className="command-ribbon" aria-label="Active mode and model ribbon">
            <article className="command-ribbon__card command-ribbon__card--mode">
              <span className="command-ribbon__label">Active mode</span>
              <strong>{activeModeSurface}</strong>
              <small>{activeMode.intent}</small>
            </article>
            <article className="command-ribbon__card command-ribbon__card--model">
              <span className="command-ribbon__label">Active model</span>
              <strong>{modelLaneLabel}</strong>
              <small>{modelTruthLabel}</small>
            </article>
            <article className="command-ribbon__card">
              <span className="command-ribbon__label">Runtime truth</span>
              <strong>{runtimeRecentActivity.length > 0 || runtimeTasksLive.length > 0 || runtimeNotesLive.length > 0 ? 'Live signals present' : 'Baseline only'}</strong>
              <small>
                {runtimeRecentActivity.length > 0 || runtimeTasksLive.length > 0 || runtimeNotesLive.length > 0
                  ? `${runtimeRecentActivity.length} recent runtime events, ${runtimeTasksLive.length} runtime tasks, ${runtimeNotesLive.length} runtime notes`
                  : 'Current server data is seeded/demo baseline only; the UI labels it explicitly instead of implying live execution.'}
              </small>
            </article>
            <article className="command-ribbon__card">
              <span className="command-ribbon__label">Mode coverage</span>
              <strong>{modeCoverage.toString().padStart(2, '0')} profiles</strong>
              <small>{runtimeContext ? 'derived from runtime context' : 'falling back to local mode registry'}</small>
            </article>
          </div>

          <div className="deck-banner">
            <div className="deck-banner__callout">
              <span className="deck-banner__label">Command state</span>
              <strong>{isResponding ? 'Directive in motion' : 'Ready for directive'}</strong>
              <small>{activeMode.label} · {modelLaneLabel}</small>
            </div>
            <div className="deck-banner__meta">
              <span>{transportPreview.runtimeTarget.apiBasePath}</span>
              <span>{transportPreview.runtimeTarget.eventStreamPath}</span>
              <span>{runtimeContext?.session.persistenceDriver ?? 'local-memory'} persistence</span>
            </div>
          </div>

          <section className="overview-strip" aria-label="Command overview">
            <div className="overview-card overview-card--hot">
              <span>Thread state</span>
              <strong>{isResponding ? 'Sentinel composing' : 'Ready for directive'}</strong>
              <small>{messages.length} visible packets</small>
            </div>
            <div className="overview-card">
              <span>Active work</span>
              <strong>{attentionCounts?.active ?? activeExecutionTasks.length}</strong>
              <small>{attentionCounts?.blocked ?? blockedTasks.length} blocked · {attentionCounts?.waitingOnUser ?? waitingOnUserTasks.length} waiting</small>
            </div>
            <div className="overview-card">
              <span>Runtime notices</span>
              <strong>{systemMessages.toString().padStart(2, '0')} signals</strong>
              <small>{apiState === 'connected' ? 'server-derived context' : 'local continuity'}</small>
            </div>
            <div className="overview-card">
              <span>Latest event</span>
              <strong>{latestMessage?.author ?? 'Waiting'}</strong>
              <small>{lastEventLabel}</small>
            </div>
          </section>

          <section className="telemetry-grid" aria-label="Runtime telemetry cards">
            {runtimeCards.length > 0 ? (
              runtimeCards.map((card) => (
                <article key={card.id} className={`telemetry-card telemetry-card--${card.severity}`}>
                  <div className="telemetry-card__header">
                    <span>{card.label}</span>
                    <span className="telemetry-card__status">{card.severity}</span>
                  </div>
                  <strong>{card.value}</strong>
                  <p>{card.detail}</p>
                </article>
              ))
            ) : (
              <article className="telemetry-card telemetry-card--placeholder">
                <div className="telemetry-card__header">
                  <span>Telemetry link</span>
                  <span className="telemetry-card__status">standby</span>
                </div>
                <strong>Awaiting API snapshot</strong>
                <p>Command deck will hydrate from /api/status and /api/runtime/context when the server is reachable.</p>
              </article>
            )}
          </section>

          <section className="ops-grid ops-grid--command" aria-label="Operations overview">
            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Task progress board</p>
                  <h2>Stage-based workflow</h2>
                </div>
                <span className="status-pill status-pill--subtle">truthful stages</span>
              </div>
              <div className="stage-board">
                {stageCards.map((stage) => (
                  <div key={stage.id} className="stage-chip">
                    <span>{formatStageLabel(stage.id)}</span>
                    <strong>{stage.value}</strong>
                    <small>{stage.detail}</small>
                  </div>
                ))}
              </div>
            </article>

            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Agent activity</p>
                  <h2>Presence and execution posture</h2>
                </div>
                <span className="status-pill status-pill--subtle">local-first</span>
              </div>
              <div className="stack-list">
                {agentRoster.map((agent) => (
                  <div key={agent.id} className="stack-list__item stack-list__item--compact">
                    <div className="stack-list__row">
                      <strong>{agent.label}</strong>
                      <span className="status-pill status-pill--subtle">{agent.state}</span>
                    </div>
                    <small>{agent.detail}</small>
                  </div>
                ))}
              </div>
            </article>

            <article className="panel ops-panel ops-panel--wide">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Execution surfaces</p>
                  <h2>Operator attention board</h2>
                </div>
                <span className="status-pill status-pill--subtle">{runtimeTasksLive.length} live · {seededTasks.length} baseline</span>
              </div>
              <div className="board-grid">
                {boardGroups.map((group) => (
                  <section key={group.id} className={`board-column board-column--${group.tone}`}>
                    <div className="board-column__header">
                      <div>
                        <strong>{group.title}</strong>
                        <small>{group.description}</small>
                      </div>
                      <span className="status-pill status-pill--subtle">{group.tasks.length}</span>
                    </div>
                    <div className="board-column__body">
                      {group.tasks.length > 0 ? (
                        group.tasks.slice(0, 4).map((task) => (
                          <div key={task.id} className="task-board-card">
                            <div className="stack-list__row">
                              <strong>{task.title}</strong>
                              <span className="status-pill status-pill--subtle">{formatStageLabel(task.stage)}</span>
                            </div>
                            <small>{describeTask(task)}</small>
                            {task.summary ? <p className="muted-copy">{task.summary}</p> : null}
                            <div className="task-board-card__footer">
                              <span className="status-pill status-pill--subtle">{task.source === 'runtime' ? 'live' : 'seeded baseline'}</span>
                              <span className="status-pill status-pill--subtle">{task.status}</span>
                            </div>
                          </div>
                        ))
                      ) : (
                        <div className="task-board-card task-board-card--empty">
                          <strong>No items in this surface</strong>
                          <small>The runtime is not exposing anything here right now.</small>
                        </div>
                      )}
                    </div>
                  </section>
                ))}
              </div>
            </article>

            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Status inventory</p>
                  <h2>High-level task counts</h2>
                </div>
                <span className="status-pill status-pill--subtle">task states</span>
              </div>
              <div className="task-matrix">
                <div className="task-cell">
                  <span>Queued</span>
                  <strong>{taskBreakdown?.Queued ?? 0}</strong>
                </div>
                <div className="task-cell task-cell--live">
                  <span>In Progress</span>
                  <strong>{taskBreakdown?.['In Progress'] ?? 0}</strong>
                </div>
                <div className="task-cell task-cell--warn">
                  <span>Blocked</span>
                  <strong>{taskBreakdown?.Blocked ?? 0}</strong>
                </div>
                <div className="task-cell">
                  <span>Done</span>
                  <strong>{taskBreakdown?.Done ?? 0}</strong>
                </div>
              </div>
            </article>

            <article className="panel ops-panel ops-panel--wide">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Progress feed</p>
                  <h2>What is happening now vs seeded baseline</h2>
                </div>
                <span className="status-pill status-pill--subtle">{liveNowFeed.length} live · {baselineFeed.length} baseline</span>
              </div>
              <div className="event-list muted-copy">
                {liveNowFeed.length > 0 ? (
                  liveNowFeed.map((item) => (
                    <div key={item.id} className="event-item">
                      <div className="stack-list__row">
                        <strong>{item.title}</strong>
                        <span className="status-pill status-pill--subtle">live</span>
                      </div>
                      <span>{item.detail}</span>
                      {'meta' in item && item.meta ? <small>{item.meta}</small> : null}
                    </div>
                  ))
                ) : (
                  <div className="event-item">
                    <strong>No live runtime events yet</strong>
                    <span>The API is online, but this instance has not recorded fresh activity/notes/tasks beyond the seeded baseline.</span>
                  </div>
                )}
                {baselineFeed.length > 0 ? (
                  baselineFeed.map((item) => (
                    <div key={item.id} className="event-item">
                      <div className="stack-list__row">
                        <strong>{item.title}</strong>
                        <span className="status-pill status-pill--subtle">seeded baseline</span>
                      </div>
                      <span>{item.detail}</span>
                      {'meta' in item && item.meta ? <small>{item.meta}</small> : null}
                    </div>
                  ))
                ) : null}
              </div>
            </article>
          </section>
        </section>

        <section className="workspace-grid">
          <section className="chat-surface panel">
            <header className="surface-header">
              <div>
                <p className="eyebrow">Primary channel</p>
                <h2>Operator ↔ Sentinel</h2>
                <p className="muted-copy">
                  Terminal-weight composition, mode-specific replies, and visible transport state for every exchange.
                </p>
              </div>
              <div className="header-badges">
                <span className="status-pill">MODE · {activeModeId.toUpperCase()}</span>
                <span className="status-pill">MODEL · {apiState === 'connected' ? 'SERVER STUB' : 'LOCAL SIM'}</span>
                <span className="status-pill status-pill--subtle">{runtimeContext?.session.hostLabel ?? 'host pending'}</span>
              </div>
            </header>

            <ModeSwitch modes={modes} activeModeId={activeModeId} onSelect={setActiveModeId} />
            <ConversationView messages={messages} />
            <Composer
              draft={draft}
              historyCursorLabel={historyCursorLabel}
              isResponding={isResponding}
              activeModeLabel={activeMode.label}
              onDraftChange={(value) => setDraft({ value, historyIndex: null })}
              onSubmit={() => submitMessage(draft.value)}
              onHistory={cycleHistory}
            />
          </section>

          <aside className="right-stack">
            <section className="panel tactical-panel">
              <div className="panel-block">
                <p className="eyebrow">Operator attention</p>
                <strong>Task routing surfaces</strong>
                <div className="task-matrix">
                  <div className="task-cell task-cell--live">
                    <span>Active</span>
                    <strong>{attentionCounts?.active ?? activeExecutionTasks.length}</strong>
                  </div>
                  <div className="task-cell">
                    <span>Waiting on user</span>
                    <strong>{attentionCounts?.waitingOnUser ?? waitingOnUserTasks.length}</strong>
                  </div>
                  <div className="task-cell task-cell--warn">
                    <span>Blocked</span>
                    <strong>{attentionCounts?.blocked ?? blockedTasks.length}</strong>
                  </div>
                  <div className="task-cell">
                    <span>Ready to report</span>
                    <strong>{attentionCounts?.readyToReport ?? readyToReportTasks.length}</strong>
                  </div>
                </div>
              </div>
            </section>

            <section className="panel tactical-panel">
              <div className="panel-block">
                <p className="eyebrow">Field notes</p>
                <strong>Project memory + operator doctrine</strong>
                <div className="detail-stack muted-copy">
                  {runtimeNotes.length > 0 ? (
                    runtimeNotes.slice(0, 3).map((note) => (
                      <span key={note.id}>
                        [{note.tag}] {note.title} — {note.body} ({note.source === 'runtime' ? 'live' : 'seeded baseline'})
                      </span>
                    ))
                  ) : (
                    <span>No runtime notes are visible yet.</span>
                  )}
                </div>
              </div>
            </section>

            <PersonaPanel
              activeMode={activeMode}
              transportPreview={transportPreview}
              runtimeContext={runtimeContext}
              runtimeStatus={runtimeStatus}
              suggestedPrompts={suggestedPrompts}
              historyCount={inputHistory.length}
              recentActivity={recentActivity}
              onPromptSelect={(prompt) => setDraft({ value: prompt, historyIndex: null })}
            />
          </aside>
        </section>
      </main>
    </div>
  )
}

export default App
