import './App.css'
import { Composer } from './features/chat/components/Composer'
import { ConversationView } from './features/chat/components/ConversationView'
import { ModeSwitch } from './features/chat/components/ModeSwitch'
import { PersonaPanel } from './features/chat/components/PersonaPanel'
import { useLocalChat } from './features/chat/hooks/useLocalChat'

function formatLastEventLabel(timestamp: string | undefined) {
  if (!timestamp) return 'Awaiting first packet'
  const parsed = Date.parse(timestamp)
  if (Number.isNaN(parsed)) return timestamp

  return new Intl.DateTimeFormat(undefined, {
    hour: '2-digit',
    minute: '2-digit',
    month: 'short',
    day: 'numeric',
  }).format(parsed)
}

function App() {
  const {
    activeMode,
    activeModeId,
    apiState,
    draft,
    historyCursorLabel,
    inputHistory,
    isResponding,
    messages,
    modes,
    rawMessages,
    recentActivity,
    runtimeContext,
    runtimeNotes,
    runtimeStatus,
    runtimeTasks,
    suggestedPrompts,
    transportPreview,
    setActiveModeId,
    setDraft,
    submitMessage,
    cycleHistory,
  } = useLocalChat()

  const latestMessage = rawMessages[rawMessages.length - 1]
  const operatorMessages = rawMessages.filter((message) => message.role === 'operator').length
  const systemMessages = rawMessages.filter((message) => message.role === 'system').length
  const taskBreakdown = runtimeContext?.surfaces.taskBreakdown
  const runtimeCards = runtimeStatus?.cards ?? []
  const environmentLabel = runtimeStatus?.environment ?? 'offline'
  const lastEventLabel = formatLastEventLabel(latestMessage?.timestamp)
  const activeTasks = runtimeTasks.filter((task) => task.status !== 'Done')
  const urgentTasks = runtimeTasks.filter((task) => task.status === 'Blocked' || task.status === 'In Progress')
  const modeCoverage = runtimeContext?.chat.modes.length ?? modes.length
  const activeModeSurface = activeMode.label
  const activeModeAccent = activeMode.accent
  const modelLaneLabel =
    apiState === 'connected'
      ? 'Server stub response'
      : transportPreview.provider === 'Local simulator'
        ? 'Local simulator'
        : transportPreview.provider
  const modelTruthLabel =
    apiState === 'connected'
      ? 'Model identity not yet exposed by backend. Current replies are honest server-side placeholder responses.'
      : 'No backend model truth available. Responses are generated by the local simulator seam.'
  const projectAreas = [
    {
      id: 'delivery',
      title: 'Project areas',
      value: `${activeTasks.length} active items`,
      detail:
        activeTasks[0]?.title ?? 'No active tasks exposed yet. Runtime can still hydrate this surface later.',
    },
    {
      id: 'board',
      title: 'Execution board',
      value: `${runtimeTasks.length} tracked tasks`,
      detail:
        runtimeTasks[0]?.title ?? 'Board is structurally ready; richer prioritization arrives when backend state expands.',
    },
    {
      id: 'agents',
      title: 'Agent activity',
      value: `${recentActivity.length} visible signals`,
      detail:
        recentActivity[0]?.title ?? 'Waiting on richer runtime events for deeper agent and subagent telemetry.',
    },
    {
      id: 'memory',
      title: 'Progress feed',
      value: `${runtimeNotes.length} field notes`,
      detail: runtimeNotes[0]?.title ?? 'Local-first notes surface stays usable even when the API is dark.',
    },
  ]

  const executionBoard = runtimeTasks.slice(0, 5)
  const progressFeed = [...recentActivity, ...runtimeNotes.map((note) => ({
    id: note.id,
    title: note.title,
    detail: note.body,
    status: 'logged' as const,
    meta: `[${note.tag}] ${note.updatedAt}`,
  }))].slice(0, 6)
  const agentRoster = [
    {
      id: 'sentinel',
      label: 'Sentinel core',
      state: isResponding ? 'engaged' : apiState === 'connected' ? 'synced' : 'local-only',
      detail: `${activeMode.label} · ${modelLaneLabel}`,
    },
    {
      id: 'runtime',
      label: 'Runtime spine',
      state: apiState === 'connected' ? 'live' : 'standby',
      detail: runtimeContext
        ? `${runtimeContext.session.hostLabel} · ${runtimeContext.session.persistenceDriver}`
        : 'Awaiting bootstrap context',
    },
    {
      id: 'task-grid',
      label: 'Task grid',
      state: urgentTasks.length > 0 ? 'watch' : 'steady',
      detail: `${runtimeTasks.length} tracked tasks · ${taskBreakdown?.Blocked ?? 0} blocked`,
    },
    {
      id: 'model-monitor',
      label: 'System/model monitor',
      state: apiState === 'connected' ? 'truthful' : 'fallback',
      detail: modelTruthLabel,
    },
  ]

  const runtimeSummary = runtimeContext
    ? `${runtimeContext.session.hostLabel} · ${runtimeContext.chat.messageCount} persisted messages · ${runtimeContext.surfaces.tasksCount} tracked tasks · ${runtimeContext.surfaces.activityCount} visible updates`
    : 'Server-derived session context not available yet. Local shell remains armed.'

  return (
    <div className="app-shell">
      <div className="shell-backdrop" aria-hidden="true">
        <div className="shell-backdrop__grid" />
        <div className="shell-backdrop__glow shell-backdrop__glow--one" />
        <div className="shell-backdrop__glow shell-backdrop__glow--two" />
      </div>

      <aside className="left-rail">
        <div className="brand-block">
          <p className="eyebrow">Sentinel Nexus // Command Center</p>
          <h1>Operator shell for decisive work, runtime visibility, and controlled execution.</h1>
          <p className="muted-copy">
            A cinematic local-first command surface with live backend truth when available and explicit seams where it is not.
          </p>
        </div>

        <div className="rail-card rail-card--accent">
          <div className="rail-card__header">
            <p className="eyebrow">System posture</p>
            <span className={`status-pill ${isResponding ? 'status-pill--live' : ''}`}>
              {isResponding ? 'LIVE TRAFFIC' : apiState === 'connected' ? 'SYNCED' : 'LOCAL FALLBACK'}
            </span>
          </div>
          <strong>{activeMode.label}</strong>
          <p className="muted-copy">{activeMode.intent}</p>
          <div className="rail-signal">
            <span className="rail-signal__label">Model lane</span>
            <span>{modelLaneLabel}</span>
          </div>
          <div className="rail-signal">
            <span className="rail-signal__label">Transport</span>
            <span>{transportPreview.provider}</span>
          </div>
        </div>

        <div className="rail-grid">
          <div className="rail-metric rail-metric--emphasis">
            <span>Active mode</span>
            <strong>{activeModeId.toUpperCase()}</strong>
            <small>{activeModeAccent}</small>
          </div>
          <div className="rail-metric rail-metric--emphasis">
            <span>Active model</span>
            <strong>{apiState === 'connected' ? 'SERVER STUB' : 'LOCAL SIM'}</strong>
            <small>{apiState === 'connected' ? 'backend truth boundary' : 'offline/local seam'}</small>
          </div>
          <div className="rail-metric">
            <span>History</span>
            <strong>{inputHistory.length.toString().padStart(2, '0')}</strong>
            <small>prompt recalls</small>
          </div>
          <div className="rail-metric">
            <span>Runtime</span>
            <strong>{environmentLabel}</strong>
            <small>{apiState === 'connected' ? 'API present' : 'simulated adapter'}</small>
          </div>
        </div>

        <div className="rail-card">
          <p className="eyebrow">Runtime sync</p>
          <strong>{apiState === 'connected' ? 'Backend connected' : 'Local continuity mode'}</strong>
          <p className="muted-copy">{runtimeSummary}</p>
        </div>

        <div className="rail-card">
          <p className="eyebrow">Command-center lanes</p>
          <div className="stack-list">
            {projectAreas.map((area) => (
              <div key={area.id} className="stack-list__item">
                <span>{area.title}</span>
                <strong>{area.value}</strong>
                <small>{area.detail}</small>
              </div>
            ))}
          </div>
        </div>
      </aside>

      <main className="workspace">
        <section className="command-deck panel">
          <div>
            <p className="eyebrow">Command deck</p>
            <h2>Sentinel runtime monitor</h2>
            <p className="muted-copy">
              Real storage, message, task, and activity surfaces route in from the Nexus API when online. Offline, the shell keeps local composure and advertises the seam.
            </p>
          </div>

          <div className="command-ribbon" aria-label="Active mode and model ribbon">
            <article className="command-ribbon__card command-ribbon__card--mode">
              <span className="command-ribbon__label">Active mode</span>
              <strong>{activeModeSurface}</strong>
              <small>{activeMode.intent}</small>
            </article>
            <article className="command-ribbon__card command-ribbon__card--model">
              <span className="command-ribbon__label">Active model</span>
              <strong>{modelLaneLabel}</strong>
              <small>{modelTruthLabel}</small>
            </article>
            <article className="command-ribbon__card">
              <span className="command-ribbon__label">Mode coverage</span>
              <strong>{modeCoverage.toString().padStart(2, '0')} profiles</strong>
              <small>{runtimeContext ? 'derived from runtime context' : 'falling back to local mode registry'}</small>
            </article>
          </div>

          <div className="deck-banner">
            <div className="deck-banner__callout">
              <span className="deck-banner__label">Command state</span>
              <strong>{isResponding ? 'Directive in motion' : 'Ready for directive'}</strong>
              <small>{activeMode.label} · {modelLaneLabel}</small>
            </div>
            <div className="deck-banner__meta">
              <span>{transportPreview.runtimeTarget.apiBasePath}</span>
              <span>{transportPreview.runtimeTarget.eventStreamPath}</span>
              <span>{runtimeContext?.session.persistenceDriver ?? 'local-memory'} persistence</span>
            </div>
          </div>

          <section className="overview-strip" aria-label="Command overview">
            <div className="overview-card overview-card--hot">
              <span>Thread state</span>
              <strong>{isResponding ? 'Sentinel composing' : 'Ready for directive'}</strong>
              <small>{messages.length} visible packets</small>
            </div>
            <div className="overview-card">
              <span>Operator activity</span>
              <strong>{operatorMessages.toString().padStart(2, '0')} prompts</strong>
              <small>{historyCursorLabel}</small>
            </div>
            <div className="overview-card">
              <span>Runtime notices</span>
              <strong>{systemMessages.toString().padStart(2, '0')} signals</strong>
              <small>{apiState === 'connected' ? 'server-derived context' : 'local continuity'}</small>
            </div>
            <div className="overview-card">
              <span>Latest event</span>
              <strong>{latestMessage?.author ?? 'Waiting'}</strong>
              <small>{lastEventLabel}</small>
            </div>
          </section>

          <section className="telemetry-grid" aria-label="Runtime telemetry cards">
            {runtimeCards.length > 0 ? (
              runtimeCards.map((card) => (
                <article key={card.id} className={`telemetry-card telemetry-card--${card.severity}`}>
                  <div className="telemetry-card__header">
                    <span>{card.label}</span>
                    <span className="telemetry-card__status">{card.severity}</span>
                  </div>
                  <strong>{card.value}</strong>
                  <p>{card.detail}</p>
                </article>
              ))
            ) : (
              <article className="telemetry-card telemetry-card--placeholder">
                <div className="telemetry-card__header">
                  <span>Telemetry link</span>
                  <span className="telemetry-card__status">standby</span>
                </div>
                <strong>Awaiting API snapshot</strong>
                <p>Command deck will hydrate from /api/status and /api/runtime/context when the server is reachable.</p>
              </article>
            )}
          </section>

          <section className="ops-grid ops-grid--command" aria-label="Operations overview">
            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Project areas</p>
                  <h2>Operational lanes</h2>
                </div>
                <span className="status-pill status-pill--subtle">mission map</span>
              </div>
              <div className="stack-list">
                {projectAreas.map((area) => (
                  <div key={area.id} className="stack-list__item stack-list__item--compact">
                    <div className="stack-list__row">
                      <strong>{area.title}</strong>
                      <span className="status-pill status-pill--subtle">{area.value}</span>
                    </div>
                    <small>{area.detail}</small>
                  </div>
                ))}
              </div>
            </article>

            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Agent activity</p>
                  <h2>Presence and execution posture</h2>
                </div>
                <span className="status-pill status-pill--subtle">local-first</span>
              </div>
              <div className="stack-list">
                {agentRoster.map((agent) => (
                  <div key={agent.id} className="stack-list__item stack-list__item--compact">
                    <div className="stack-list__row">
                      <strong>{agent.label}</strong>
                      <span className="status-pill status-pill--subtle">{agent.state}</span>
                    </div>
                    <small>{agent.detail}</small>
                  </div>
                ))}
              </div>
            </article>

            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Execution board</p>
                  <h2>Tracked work by lane</h2>
                </div>
                <span className="status-pill status-pill--subtle">{runtimeTasks.length} tasks</span>
              </div>
              <div className="stack-list">
                {executionBoard.length > 0 ? (
                  executionBoard.map((task) => (
                    <div key={task.id} className="stack-list__item stack-list__item--compact">
                      <div className="stack-list__row">
                        <strong>{task.title}</strong>
                        <span className="status-pill status-pill--subtle">{task.status}</span>
                      </div>
                      <small>{task.lane} · {task.owner} · due {task.due}</small>
                    </div>
                  ))
                ) : (
                  <div className="stack-list__item stack-list__item--compact">
                    <strong>No runtime tasks yet</strong>
                    <small>Task inventory will appear here when bootstrap/task state is available.</small>
                  </div>
                )}
              </div>
            </article>

            <article className="panel ops-panel">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">System/model monitor</p>
                  <h2>Truth boundary and runtime lane</h2>
                </div>
                <span className="status-pill status-pill--subtle">honest telemetry</span>
              </div>
              <div className="stack-list">
                <div className="stack-list__item stack-list__item--compact">
                  <div className="stack-list__row">
                    <strong>Model lane</strong>
                    <span className="status-pill status-pill--subtle">{apiState === 'connected' ? 'backend stub' : 'local fallback'}</span>
                  </div>
                  <small>{modelTruthLabel}</small>
                </div>
                <div className="stack-list__item stack-list__item--compact">
                  <div className="stack-list__row">
                    <strong>Persistence</strong>
                    <span className="status-pill status-pill--subtle">{runtimeStatus?.storage.driver ?? 'browser/local'}</span>
                  </div>
                  <small>
                    {runtimeStatus
                      ? `${runtimeStatus.storage.dataPath} · schema ${runtimeStatus.storage.schemaPath}`
                      : 'No server storage metadata yet. UI will continue using local recall and fallback messaging.'}
                  </small>
                </div>
              </div>
            </article>

            <article className="panel ops-panel ops-panel--wide">
              <div className="surface-header">
                <div>
                  <p className="eyebrow">Progress feed</p>
                  <h2>Recent movement across activity and notes</h2>
                </div>
                <span className="status-pill status-pill--subtle">{progressFeed.length} entries</span>
              </div>
              <div className="event-list muted-copy">
                {progressFeed.length > 0 ? (
                  progressFeed.map((item) => (
                    <div key={item.id} className="event-item">
                      <div className="stack-list__row">
                        <strong>{item.title}</strong>
                        <span className={`status-dot status-dot--${item.status}`} />
                      </div>
                      <span>{item.detail}</span>
                      {'meta' in item && item.meta ? <small>{item.meta}</small> : null}
                    </div>
                  ))
                ) : (
                  <div className="event-item">
                    <strong>Feed is quiet</strong>
                    <span>Activity will populate from bootstrap and future runtime events.</span>
                  </div>
                )}
              </div>
            </article>
          </section>
        </section>

        <section className="workspace-grid">
          <section className="chat-surface panel">
            <header className="surface-header">
              <div>
                <p className="eyebrow">Primary channel</p>
                <h2>Operator ↔ Sentinel</h2>
                <p className="muted-copy">
                  Terminal-weight composition, mode-specific replies, and visible transport state for every exchange.
                </p>
              </div>
              <div className="header-badges">
                <span className="status-pill">MODE · {activeModeId.toUpperCase()}</span>
                <span className="status-pill">MODEL · {apiState === 'connected' ? 'SERVER STUB' : 'LOCAL SIM'}</span>
                <span className="status-pill status-pill--subtle">{runtimeContext?.session.hostLabel ?? 'host pending'}</span>
              </div>
            </header>

            <ModeSwitch modes={modes} activeModeId={activeModeId} onSelect={setActiveModeId} />
            <ConversationView messages={messages} />
            <Composer
              draft={draft}
              historyCursorLabel={historyCursorLabel}
              isResponding={isResponding}
              activeModeLabel={activeMode.label}
              onDraftChange={(value) => setDraft({ value, historyIndex: null })}
              onSubmit={() => submitMessage(draft.value)}
              onHistory={cycleHistory}
            />
          </section>

          <aside className="right-stack">
            <section className="panel tactical-panel">
              <div className="panel-block">
                <p className="eyebrow">Task matrix</p>
                <strong>Backend execution breakdown</strong>
                <div className="task-matrix">
                  <div className="task-cell">
                    <span>Queued</span>
                    <strong>{taskBreakdown?.Queued ?? 0}</strong>
                  </div>
                  <div className="task-cell task-cell--live">
                    <span>In Progress</span>
                    <strong>{taskBreakdown?.['In Progress'] ?? 0}</strong>
                  </div>
                  <div className="task-cell task-cell--warn">
                    <span>Blocked</span>
                    <strong>{taskBreakdown?.Blocked ?? 0}</strong>
                  </div>
                  <div className="task-cell">
                    <span>Done</span>
                    <strong>{taskBreakdown?.Done ?? 0}</strong>
                  </div>
                </div>
              </div>
            </section>

            <section className="panel tactical-panel">
              <div className="panel-block">
                <p className="eyebrow">Field notes</p>
                <strong>Project memory + operator doctrine</strong>
                <div className="detail-stack muted-copy">
                  {runtimeNotes.length > 0 ? (
                    runtimeNotes.slice(0, 3).map((note) => (
                      <span key={note.id}>
                        [{note.tag}] {note.title} — {note.body}
                      </span>
                    ))
                  ) : (
                    <span>No runtime notes are visible yet.</span>
                  )}
                </div>
              </div>
            </section>

            <PersonaPanel
              activeMode={activeMode}
              transportPreview={transportPreview}
              runtimeContext={runtimeContext}
              runtimeStatus={runtimeStatus}
              suggestedPrompts={suggestedPrompts}
              historyCount={inputHistory.length}
              recentActivity={recentActivity}
              onPromptSelect={(prompt) => setDraft({ value: prompt, historyIndex: null })}
            />
          </aside>
        </section>
      </main>
    </div>
  )
}

export default App
